// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuM294LlukeqbNKC8rspyhGGj4oM_k4qo',
    appId: '1:585654128265:web:51ed9afeb38ba5122c8058',
    messagingSenderId: '585654128265',
    projectId: 'ecommerce-b4772',
    authDomain: 'ecommerce-b4772.firebaseapp.com',
    storageBucket: 'ecommerce-b4772.appspot.com',
    measurementId: 'G-FZQBV8T98J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcV1_Zxjnjyh1arIKXSJLVGRiOuhVKG6A',
    appId: '1:585654128265:android:26a939f0b6f305bf2c8058',
    messagingSenderId: '585654128265',
    projectId: 'ecommerce-b4772',
    storageBucket: 'ecommerce-b4772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-zCnXwSlfnokCC0ot9bQcrj7_hRBhQOM',
    appId: '1:585654128265:ios:6317daa62cb688742c8058',
    messagingSenderId: '585654128265',
    projectId: 'ecommerce-b4772',
    storageBucket: 'ecommerce-b4772.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-zCnXwSlfnokCC0ot9bQcrj7_hRBhQOM',
    appId: '1:585654128265:ios:c9174c9fdaae31352c8058',
    messagingSenderId: '585654128265',
    projectId: 'ecommerce-b4772',
    storageBucket: 'ecommerce-b4772.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
